/*
Copyright 2021 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type GitSource struct {
	// If importing from git, the repository to create the component from
	URL string `json:"url"`

	// Specify a branch/tag/commit id. If not specified, default is `main`/`master`.
	Revision string `json:"revision,omitempty"`

	// A relative path inside the git repo containing the component
	Context string `json:"context,omitempty"`

	// If specified, the devfile at the URL will be used for the component.
	DevfileURL string `json:"devfileUrl,omitempty"`

	// If specified, the dockerfile at the URL will be used for the component.
	DockerfileURL string `json:"dockerfileUrl,omitempty"`
}

// ComponentSource describes the Component source
type ComponentSource struct {
	ComponentSourceUnion `json:",inline"`
}

type ComponentSourceUnion struct {
	// Git Source for a Component
	GitSource *GitSource `json:"git,omitempty"`
}

// ComponentSpec defines the desired state of Component
type ComponentSpec struct {
	// ComponentName is name of the component to be added to the HASApplication
	ComponentName string `json:"componentName"`

	// Application to add the component to
	Application string `json:"application"`

	// Secret describes the name of a Kubernetes secret containing either:
	// 1. A Personal Access Token to access the Component's git repostiory (if using a Git-source component) or
	// 2. An Image Pull Secret to access the Component's container image (if using an Image-source component).
	Secret string `json:"secret,omitempty"`

	// Source describes the Component source
	Source ComponentSource `json:"source,omitempty"`

	// Compute Resources required by this component
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// The number of replicas to deploy the component with
	Replicas int `json:"replicas,omitempty"`

	// The port to expose the component over
	TargetPort int `json:"targetPort,omitempty"`

	// The route to expose the component with
	Route string `json:"route,omitempty"`

	// An array of environment variables to add to the component
	Env []corev1.EnvVar `json:"env,omitempty"`

	// The container image to build or create the component from
	ContainerImage string `json:"containerImage,omitempty"`

	// Whether or not to bypass the generation of GitOps resources for the Component. Defaults to false.
	SkipGitOpsResourceGeneration bool `json:"skipGitOpsResourceGeneration,omitempty"`
}

// ComponentStatus defines the observed state of Component
type ComponentStatus struct {
	// Condition about the Component CR
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// Webhook URL generated by Builds
	Webhook string `json:"webhook,omitempty"`

	// ContainerImage stores the associated built container image for the component
	ContainerImage string `json:"containerImage,omitempty"`

	// The devfile model for the Component CR
	Devfile string `json:"devfile,omitempty"`

	// GitOps specific status for the Component CR
	GitOps GitOpsStatus `json:"gitops,omitempty"`
}

// GitOpsStatus contains GitOps repository-specific status for the component
type GitOpsStatus struct {
	// RepositoryURL is the gitops repository URL for the component
	RepositoryURL string `json:"repositoryURL,omitempty"`

	// Branch is the branch used for the gitops repository
	Branch string `json:"branch,omitempty"`

	// Context is the path within the gitops repository used for the gitops resources
	Context string `json:"context,omitempty"`

	// ResourceGenerationSkipped is whether or not GitOps resource generation was skipped for the component
	ResourceGenerationSkipped bool `json:"resourceGenerationSkipped,omitempty"`

	// CommitID is the most recent commit ID in the GitOps repository for this component
	CommitID string `json:"commitID,omitempty"`
}

// Component is the Schema for the components API
type Component struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ComponentSpec   `json:"spec,omitempty"`
	Status ComponentStatus `json:"status,omitempty"`
}

type BindingComponentConfiguration struct {

	// Name is the name of the component.
	Name string `json:"name"`

	// Replicas defines the number of replicas to use for the component
	Replicas int `json:"replicas"`

	// Resources defines the Compute Resources required by the component
	Resources *corev1.ResourceRequirements `json:"resources,omitempty"`

	// Env describes environment variables to use for the component
	Env []corev1.EnvVar `json:"env,omitempty"`
}

type EnvironmentConfiguration struct {
	// Env is an array of standard environment variables
	Env []corev1.EnvVar `json:"env"`
}

type EnvironmentSpec struct {
	// Configuration contains environment-specific details for Applications/Components that are deployed to
	// the Environment.
	Configuration EnvironmentConfiguration `json:"configuration,omitempty"`
}

type Environment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EnvironmentSpec `json:"spec,omitempty"`
}
